name: lando-tooling
compose:
  - compose.yml
events:
  post-start:
    - node: whoami | grep node
    - echo "$PRIMARY_SERVICE" | grep yes
services:
  node:
    api: 3
    type: lando
    meUser: node
    services:
      image: node:16
      command: docker-entrypoint.sh sleep infinity
      environment:
        PRIMARY_SERVICE: yes
        LANDO_WEBROOT_USER: 'node'
        LANDO_WEBROOT_GROUP: 'node'
        LANDO_WEBROOT_UID: '1000'
        LANDO_WEBROOT_GID: '1000'
  l337-node:
    api: 4
    image: node:16
    command: sleep infinity
    meUser: node
    volumes:
      - "./:/app"
    environment:
      SERVICE: l337-node
  l337-php:
    api: 4
    image: php:7.1-fpm-alpine
    volumes:
      - "./:/web"
  l337-slim:
    api: 4
    command: sleep infinity
    image: alpine:3.18.3
    meUser: root
    working_dir: /tmp

tooling:
  php:
    service: php
    description: Run php commands
    cmd: php
  iamroot:
    cmd: echo "$HOME" && echo "$(id)" > /whoami
    user: root
    service: :service
    options:
      service:
        default: php
        alias:
          - s
        describe: Runs in this service
  whoami:
    cmd: whoami
    service: :service
    options:
      service:
        default: php
        alias:
          - s
        describe: Runs in this service
  nodeme:
    cmd: whoami
    service: :service
    options:
      service:
        default: node
        alias:
          - s
        describe: Runs in this service
  stillme:
    cmd:
      - node: whoami | grep node
      - l337-node: whoami | grep node
  notme:
    cmd: whoami
    service: :service
    user: www-data
    options:
      service:
        default: node
        alias:
          - s
        describe: Runs in this service
  pipesandstuff:
    service: node
    cmd:
      - env | grep LANDO_ > pipe.txt
      - echo "more" >> pipe.txt
  test:
    service: php
    cmd:
      - php -v
      - php -m
    description: Run all the tests
  test2:
    service: l337-php
    cmd:
      - php -v
      - php -m
    description: Run all the tests 2
  word:
    service: :service
    cmd: /app/word.sh
    level: app
    options:
      service:
        default: web
        alias:
          - s
        describe: Runs in this service
      word:
        passthrough: true
        alias:
          - w
        describe: Print what the word is
        interactive:
          type: input
          message: What is the word?
          default: bird
          weight: 600
  word-engine [word]:
    service: :service
    cmd: /app/word-engine.sh
    level: engine
    options:
      service:
        default: web
        alias:
          - s
        describe: Runs in this service
      random:
        passthrough: true
        alias:
          - w
        describe: Random number
        interactive:
          type: input
          message: What is the random number?
          default: 7
          weight: 600
  lonely-bird:
    service: web
    cmd: /app/word.sh
  dynamic:
    cmd: env
    service: :service
    options:
      service:
        default: web
        alias:
          - s
        describe: Runs in this service
  env:
    cmd:
      - php: env | grep SERVICE | grep php
      - web: env | grep SERVICE | grep web
      - l337-node: env | grep SERVICE | grep l337-node
    description: Print service names for php, web, l337-node
  busted:
    service: web
    cmd: i-do-not-exist
  envvar:
    service: web
    cmd: echo "$TAYLOR"
    env:
      TAYLOR: swift
  listfiles:
    service: web
    cmd: ls -lsa /app/*
  cmdsub:
    service: web
    cmd: echo "`ls -lsa /app/*`"
  oneliner:
    service: web
    cmd: if [ ! -z "$SPECIAL" ]; then echo "$SPECIAL"; fi
    env:
      SPECIAL: HOLLA
  workdir:
    cmd: pwd
    service: web
    dir: /tmp
  pwd:
    cmd: pwd
    service: :service
    options:
      service:
        default: web
        alias:
          - s
        describe: Runs in this service
  'pwd-app [file]':
    cmd: pwd
    service: :container
    options:
      container:
        default: node
        alias:
          - s
        describe: Runs in this service
  bad-tool: disabled
  naughty-tool: false

plugins:
  "@lando/core": "../.."
