name: solo-base
services:
  node:
    api: 3
    type: lando
    services:
      image: node:16
      command: docker-entrypoint.sh sleep infinity
  node2:
    api: 4
    type: l337
    image: node:14
    command: sleep infinity
    volumes:
      - ./:/app
tooling:
  node:
    service: node
  node2:
    service: node2
    cmd: node
