name: core.docs
env_file:
  - lando.env
services:
  cli:
    type: node:16
    build:
      - yarn install
    scanner: false
    ssl: false
    sslExpose: false
tooling:
  node:
    service: cli
  vuepress:
    service: cli
  yarn:
    service: cli
