name: core.docs
services:
  cli:
    api: 3
    type: lando
    services:
      image: node:16
      command: sleep infinity
    build:
      - yarn install
    scanner: false
    ssl: false
    sslExpose: false
tooling:
  node:
    service: cli
  vuepress:
    service: cli
  yarn:
    service: cli
