product: lando
hyperdrive: hyperdrive
channel: stable
domain: lndo.site
mode: cli

dockerSupportedVersions:
  compose:
    satisfies: "1.x.x || 2.x.x"
    recommendUpdate: "<=2.24.6"
    tested: "<=2.26.1"
    link:
      linux: https://docs.docker.com/compose/install/#install-compose-on-linux-systems
      darwin: https://docs.docker.com/desktop/install/mac-install/
      win32: https://docs.docker.com/desktop/install/windows-install/
  desktop:
    satisfies: ">=4.0.0 <5"
    tested: "<=4.29.0"
    recommendUpdate: "<=4.28.0"
    link:
      darwin: https://docs.docker.com/desktop/install/mac-install/
      win32: https://docs.docker.com/desktop/install/windows-install/
  engine:
    satisfies: ">=18 <27"
    tested: "<=26.0.0"
    link:
      linux: https://docs.docker.com/engine/install/debian/#install-using-the-convenience-script

landoFile: .lando.yml
stats:
  - report: true
    url: https://metrics.lando.dev
