product: lando

channel: stable
domain: lndo.site
hyperdrive: hyperdrive
landoFile: .lando.yml
mode: cli
stats:
  - report: true
    url: https://metrics.lando.dev

dockerSupportedVersions:
  compose:
    satisfies: "1.x.x || 2.x.x"
    recommendUpdate: "<=2.24.6"
    tested: "<=2.29.2"
    link:
      linux: https://docs.docker.com/compose/install/#install-compose-on-linux-systems
      darwin: https://docs.docker.com/desktop/install/mac-install/
      win32: https://docs.docker.com/desktop/install/windows-install/
  desktop:
    satisfies: ">=4.0.0 <5"
    tested: "<=4.35.0"
    recommendUpdate: "<=4.34.0"
    link:
      darwin: https://docs.docker.com/desktop/install/mac-install/
      win32: https://docs.docker.com/desktop/install/windows-install/
  engine:
    satisfies: ">=18 <28"
    tested: "<=27.3.1"
    link:
      linux: https://docs.docker.com/engine/install/debian/#install-using-the-convenience-script
