name: lando-services
events:
  pre-start:
    - cat /build_as_root_internal.txt | grep root
    - cat /var/www/build.txt | grep www-data
    - cat /var/www/build_internal.txt | grep www-data
    - cat /run_as_root.txt || echo "$?" | grep 1
    - cat /run_as_root_internal.txt || echo "$?" | grep 1
    - cat /var/www/run.txt || echo "$?" | grep 1
    - cat /var/www/run_internal.txt || echo "$?" | grep 1
    - vim --version
  post-start:
    - cat /run_as_root_internal.txt | grep root
    - cat /var/www/run_internal.txt | grep www-data
    - cat /run_as_root.txt | grep root
    - cat /var/www/run.txt | grep www-data
    - /bin/sh -c 'echo "$LANDO_APP_PROJECT" | grep landoservices'
    # uncomment below to test out https://github.com/lando/core/issues/70
    # this is commented out by default because of https://github.com/actions/runner/issues/241
    # - bash /app/post-start.bash
services:
  appserver:
    api: 3
    type: lando
    services:
      image: pirog/php:7.1-fpm-custom
      command: docker-php-entrypoint sleep infinity
    build_as_root_internal:
      - echo "$(id)" > /build_as_root_internal.txt
    build_internal:
      - echo "$(id)" > /var/www/build_internal.txt
    run_as_root_internal:
      - echo "$(id)" > /run_as_root_internal.txt
    run_internal:
      - echo "$(id)" > /var/www/run_internal.txt
    build_as_root:
      - apt-get -y update && apt-get -y install vim
      # uncomment below to test out https://github.com/lando/core/issues/70
      # this is commented out by default because of https://github.com/actions/runner/issues/241
      # - bash /app/build_as_root.bash
    build:
      - echo "$(id)" > /var/www/build.txt
    run_as_root:
      - echo "$(id)" > /run_as_root.txt
    run:
      - echo "$(id)" > /var/www/run.txt
    overrides:
      build: ./php
      image: pirog/php:7.1-fpm-custom
  nginx:
    api: 3
    type: lando
    services:
      image: nginx:1.22.1
      command: /docker-entrypoint.sh nginx -g "daemon off;"
      ports:
        - 80
      volumes:
        - ./www:/usr/share/nginx/html
    run_as_root:
      - echo "$(id)" > /run_as_root.txt
      - ln -snf /usr/share/zoneinfo/America/New_York /etc/localtime
      - echo "America/New_York" > /etc/timezone
    overrides:
      environment:
        THING: STUFF
      volumes:
        - "./test.txt:/var/www/test.txt"

plugins:
  "@lando/core": "../.."
