name: lando-services
events:
  pre-start:
    - vim --version
    - cat /build_as_root_internal.txt | grep root
    - cat /var/www/build.txt | grep www-data
    - cat /var/www/build_internal.txt | grep www-data
    - cat /run_as_root.txt || echo "$?" | grep 1
    - cat /run_as_root_internal.txt || echo "$?" | grep 1
    - cat /var/www/run.txt || echo "$?" | grep 1
    - cat /var/www/run_internal.txt || echo "$?" | grep 1
  post-start:
    - cat /run_as_root_internal.txt | grep root
    - cat /var/www/run_internal.txt | grep www-data
    - cat /run_as_root.txt | grep root
    - cat /var/www/run.txt | grep www-data
    - /bin/sh -c 'echo "$LANDO_APP_PROJECT" | grep landoservices'
services:
  appserver:
    type: php:custom
    composer_version: "1.10.1"
    build_as_root_internal:
      - echo "$(id)" > /build_as_root_internal.txt
    build_internal:
      - echo "$(id)" > /var/www/build_internal.txt
    run_as_root_internal:
      - echo "$(id)" > /run_as_root_internal.txt
    run_internal:
      - echo "$(id)" > /var/www/run_internal.txt
    build_as_root:
      - apk update && apk add vim
    build:
      - echo "$(id)" > /var/www/build.txt
    run_as_root:
      - echo "$(id)" > /run_as_root.txt
    run:
      - echo "$(id)" > /var/www/run.txt
    overrides:
      build: ./php
      image: pirog/php:7.1-fpm-custom
  nginx:
    type: nginx
    webroot: www
    run_as_root:
      - echo "$(id)" > /run_as_root.txt
      - ln -snf /usr/share/zoneinfo/America/New_York /etc/localtime
      - echo "America/New_York" > /etc/timezone
    overrides:
      environment:
        THING: STUFF
      volumes:
        - "./test.txt:/var/www/test.txt"
