name: lando-sql-import
events:
  post-db-import:
    - database: /app/test-script.sh
    - database: echo "i-ran" > /tmp/iran.txt
    - echo "stuff"
services:
  appserver:
    type: mysql
  database:
    type: mysql
    overrides:
      volumes:
        - ./test.sql:/data/test.sql
  database2:
    type: postgres
tooling:
  mysql:
    service: database
    cmd: mysql -u root
  psqlverify:
    service: database2
    user: root
    cmd: psql -U postgres database -c "\dt"
  'db-import <file>':
    service: :host
    description: Imports a dump file into a database service
    cmd: /helpers/sql-import.sh
    user: root
    options:
      host:
        description: The database service to use
        default: database
        alias:
          - h
      no-wipe:
        description: Do not destroy the existing database before an import
        boolean: true
