proxy:
  web:
    - hostname: lando-proxy.lndo.site
      middlewares:
        - name: test
          key: headers.customresponseheaders.X-Lando-Merge
          value: kirk

plugins:
  "@lando/core": ../..
