name: lando-proxy
compose:
  - compose.yml
proxy:
  web:
    - lando-proxy.lndo.site
  web2:
    - another-way-to-eighty.lndo.site:80
  web3:
    - hostname: web5.lndo.site
      port: 8080
  l337:
    - hostname: l337.lndo.site
      port: 8888
    - hostname: headers.l337.lndo.site
      port: 8888
      middlewares:
        - name: test
          key: headers.customresponseheaders.X-Lando-Test
          value: on
  web4:
    - hostname: lando4.lndo.site
      port: 8080
  web5:
    - another-web.lndo.site:8888
  php:
    - hostname: object-format.lndo.site
      port: 80
      middlewares:
        - name: test
          key: headers.customrequestheaders.X-Lando-Test
          value: on
        - name: test-secured
          key: headers.customrequestheaders.X-Lando-Test-SSL
          value: on

services:
  l337:
    api: 4
    type: l337
    image: nginx:1.22.1
    volumes:
      - "./:/app"
      - "./default.conf.template:/etc/nginx/templates/default.conf.template"
    ports:
      - "8888/http"
    environment:
      NGINX_PORT: "8888"
      NGINX_WEBROOT: "/app"
      NGINX_SERVER_NAME: "l337"
  php:
    api: 3
    type: lando
    ssl: true
    sslExpose: false
    services:
      image: php:7.4-apache
      command: docker-php-entrypoint apache2-foreground
      volumes:
        - "./web:/var/www/html"
      ports:
        - "80"
  web3:
    api: 3
    type: lando
    ssl: true
    sslExpose: false
    services:
      image: bitnamilegacy/nginx
      command: /opt/bitnami/scripts/nginx/entrypoint.sh /opt/bitnami/scripts/nginx/run.sh
      volumes:
        - "./:/app"
      ports:
        - "8080"
      user: root
  web4:
    api: 4
    type: lando
    image:
      imagefile: nginxinc/nginx-unprivileged:1.26.1
      context:
        - ./default-ssl.conf:/etc/nginx/conf.d/default.conf
    certs: /certs/cert.crt
    ports:
      - 8080/http
      - 8443/https
    app-mount:
      destination: /usr/share/nginx/html
  web5:
    api: 4
    image: nginx:1.22.1
    command: /docker-entrypoint.sh nginx -g "daemon off;"
    certs: false
    volumes:
      - "./default.conf.template:/etc/nginx/templates/default.conf.template"
    ports:
      - "8888/http"
    user: root
    environment:
      NGINX_PORT: "8888"
      NGINX_WEBROOT: "/app"
      NGINX_SERVER_NAME: "l337"

plugins:
  "@lando/core": ../..
