name: lando-lemp
proxy:
  appserver_nginx:
    - lando-lemp.lndo.site:8080
services:
  appserver_nginx:
    api: 4
    type: lando
    user: nginx
    healthcheck: curl -I https://lando-lemp.lndo.site
    image:
      imagefile: nginxinc/nginx-unprivileged:1.26.1
      context:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080/http
      - 8443/https
    app-mount:
      destination: /var/www/html
    links:
      - appserver
    depends_on:
      - appserver
  appserver:
    api: 4
    type: l337
    image: php:8.2-fpm
    volumes:
      - ./:/var/www/html
  database:
    api: 4
    type: l337
    image: mariadb:10.4
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: da
      MARIADB_MYSQL_LOCALHOST_USER: da
      MARIADB_DATABASE: test
      MARIADB_USER: test
      MARIADB_PASSWORD: test
      MARIADB_AUTO_UPGRADE: da

plugins:
  "@lando/core": "../../.."
  "@lando/healthcheck": "../../../plugins/healthcheck"
  "@lando/networking": "../../../plugins/networking"
  "@lando/proxy": "../../../plugins/proxy"
  "@lando/scanner": "../../../plugins/scanner"
