name: lando-events
compose:
  - compose.yml
events:
  pre-start:
    - mkdir -p /app/test && echo "$(hostname -s)" > /app/test/appserver-pre-start.txt
    - web: mkdir -p /app/test && echo "$(hostname -s)" > /app/test/web-pre-start.txt
  post-start:
    - web: mkdir -p /app/test && echo "$(hostname -s)" > /app/test/web-post-start.txt
  post-thing:
    - web: mkdir -p /app/test && echo "$(hostname -s)" > /app/test/web-post-thing.txt
    - env | grep "SERVICE=web"
  pre-rebuild:
    - web: mkdir -p /app/test && echo "rebuilding" > /app/test/web-pre-rebuild.txt
  post-rebuild:
    - web: echo "ET TU, BRUT?"
  post-dynamic:
    - web: env | grep "SERVICE=web"
    - echo "thing"
  pre-destroy:
    - web: mkdir -p /app/test && touch /app/test/destroy.txt
tooling:
  thing:
    service: web
    cmd: echo "THINGS"
  dynamic:
    cmd: env
    service: :host
    options:
      host:
        default: web
        alias:
          - h
        describe: Run a different service
