name: lando-keys
services:
  cli:
    api: 3
    type: lando
    services:
      image: php:8.2-cli
      command: docker-php-entrypoint sleep infinity
      environment:
        DEBIAN_FRONTEND: noninteractive
    build_as_root:
      - apt-get -y update && apt-get -yq -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install openssh-client
      - yes y | ssh-keygen -t rsa -N '' -C 'BADBADKEY' -f /lando/keys/badbadkey
  l337-cli:
    api: 4
    type: l337
    image: php:8.2-cli
    command: sleep infinity
    volumes:
      - ./:/app

  cli2:
    api: 3
    type: lando
    services:
      image: php:8.2-cli
      command: docker-php-entrypoint sleep infinity
    build_as_root:
      - chmod 700 /lando/keys/ppkey
      - chmod 644 /lando/keys/ppkey.pub
    overrides:
      volumes:
        - ./ppkey:/lando/keys/ppkey
        - ./ppkey.pub:/lando/keys/ppkey.pub
        - "./ppkey:/lando/keys/key with space"
        - "./ppkey.pub:/lando/keys/key with space.pub"
        - ./index.html:/tmp/things
  nokeys:
    api: 3
    type: lando
    services:
      image: php:8.2-cli
      command: docker-php-entrypoint sleep infinity
    overrides:
      volumes:
        - ./config:/var/www/.ssh/config
  thesekeys:
    api: 3
    type: lando
    services:
      image: php:8.2-cli
      command: docker-php-entrypoint sleep infinity
    build_as_root:
      - chmod 700 /user/.ssh/mykey
      - chmod 700 /user/.ssh/mykey2
      - chmod 700 /user/.ssh/mykey3
    overrides:
      environment:
        LANDO_HOST_USER: Han Solo
      volumes:
        - ./easykey:/user/.ssh/mykey
        - ./easykey:/user/.ssh/mykey2
        - ./easykey:/user/.ssh/mykey3

plugins:
  "@lando/core": ../..
