name: lando-entrypoint

x-service:
  &default-service
    api: 4
    app-mount: false
    user: node
    mounts:
      - source: ./
        destination: /app
        type: copy
    ports:
      - 3000/http
    overrides:
      working_dir: /app
    build:
      image: |
        npm install

services:
  web1:
    << : *default-service
    image: node:18
    entrypoint: !load scripts/entrypoint.sh
    command: run dev
  web2:
    << : *default-service
    image: node:18
    entrypoint: npm
    command: run dev
  web3:
    << : *default-service
    image: node:18
    entrypoint: |
      #!/bin/bash
      set -eo pipefail
      npm "$@"
    command: run dev
  web4:
    << : *default-service
    image: |
      FROM node:18
      RUN echo 'npm "$@"' > /entrypoint.sh
      RUN chmod +x /entrypoint.sh
    entrypoint: /entrypoint.sh
    command: run dev
  web5:
    << : *default-service
    image: |
      FROM node:18
      ENTRYPOINT ["npm"]
      CMD ["run", "dev"]

  web6:
    << : *default-service
    image: |
      FROM node:18
      ENTRYPOINT npm run dev
      CMD doesnt matter

plugins:
  "@lando/core": ../..
