#!/bin/bash
set -eo pipefail

# Execute sh scripts in /etc/lando/boot.d
for script in /etc/lando/lash.d/*.sh; do
  if [ -e "$script" ]; then
    if [ -r "$script" ] && [ -f "$script" ]; then
      . "$script"
    fi
  fi
done
