name: lando-scanner
proxy:
  scanme:
    - lando-scanner.lndo.site
services:
  scanme:
    type: apache
  moreports:
    type: apache
    moreHttpPorts:
      - '8888'
  dontlookatme:
    type: apache
    scanner: false
  options:
    type: apache
    scanner:
      timeout: 1000
      retry: 10
      path: /another.html
      okCodes:
        - 404
  allowmissing:
    type: apache
    scanner:
      path: /missing.html
      okCodes:
        - 404
  fail:
    type: apache
    scanner:
      path: /missing.html
      retry: 4

