name: lando-scanner
proxy:
  scanme:
    - lando-scanner.lndo.site
services:
  scanme:
    api: 3
    type: lando
    services:
      image: httpd:2.4-alpine
      command: /bin/sh -c httpd-foreground
      volumes:
        - ./:/usr/local/apache2/htdocs/
      ports:
        - 80
  moreports:
    api: 3
    type: lando
    services:
      image: httpd:2.4-alpine
      command: /bin/sh -c httpd-foreground
      volumes:
        - ./:/usr/local/apache2/htdocs/
      ports:
        - 80
    moreHttpPorts:
      - '8888'
  dontlookatme:
    api: 3
    type: lando
    services:
      image: httpd:2.4-alpine
      command: /bin/sh -c httpd-foreground
      volumes:
        - ./:/usr/local/apache2/htdocs/
      ports:
        - 80
    scanner: false
  redirect:
    api: 3
    type: lando
    services:
      image: php:8.2-apache
      command: docker-php-entrypoint apache2-foreground
      volumes:
        - ./:/var/www/html/
      ports:
        - 80
    scanner:
      timeout: 1000
      retry: 10
  options:
    api: 3
    type: lando
    services:
      image: httpd:2.4-alpine
      command: /bin/sh -c httpd-foreground
      volumes:
        - ./:/usr/local/apache2/htdocs/
      ports:
        - 80
    scanner:
      timeout: 1000
      retry: 10
      path: /another.html
      okCodes:
        - 404
  allowmissing:
    api: 3
    type: lando
    services:
      image: php:8.2-apache
      command: docker-php-entrypoint apache2-foreground
      volumes:
        - ./:/var/www/html/
      ports:
        - 80
    scanner:
      path: /missing.html
      maxRedirects: 6
      okCodes:
        - 404
  fail:
    api: 3
    type: lando
    services:
      image: httpd:2.4-alpine
      command: /bin/sh -c httpd-foreground
      volumes:
        - ./:/usr/local/apache2/htdocs/
      ports:
        - 80
    scanner:
      path: /missing.html
      retry: 4
  l337:
    api: 4
    type: l337
    image:
      imagefile: nginx:1.22.1
      context:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8888
    moreHttpPorts:
      - '8888'
    volumes:
      - ./:/usr/share/nginx/html

plugins:
  "@lando/core": "../.."
  "@lando/scanner": "../../plugins/scanner"
