name: lando-exec
compose:
  - compose.yml
services:
  web2:
    api: 3
    type: lando
    build_as_root:
      - apt update -y && apt install procps -y
    services:
      image: nginx:1.22.1
      command: /docker-entrypoint.sh nginx -g "daemon off;"
      ports:
        - 0:8081
      volumes:
        - ./:/usr/share/nginx/html
  web3:
    api: 4
    type: l337
    image: |
      FROM nginx
      RUN apt update -y && apt install procps -y
    ports:
      - '80/http'
    volumes:
      - ./:/usr/share/nginx/html
  web4:
    api: 4
    type: lando
    image: |
      FROM nginxinc/nginx-unprivileged:1.26.1
      USER root
      RUN apt update -y && apt install procps -y
      USER nginx
    user: nginx
    environment:
      MESSAGE: hellothere
    ports:
      - 8080/http
    app-mount:
      destination: /usr/share/nginx/html

plugins:
  "@lando/core": ../..
