name: lando-rebuild
compose:
  - compose.yml
services:
  web2:
    api: 3
    type: lando
    services:
      image: nginx:1.22.1
      command: /docker-entrypoint.sh nginx -g "daemon off;"
      ports:
        - 0:80
      volumes:
        - ./:/usr/share/nginx/html
  web3:
    api: 4
    type: l337
    image: nginx
    ports:
      - '80/http'
    volumes:
    - ./:/usr/share/nginx/html
  web4:
    api: 4
    type: lando
    image: nginxinc/nginx-unprivileged:1.26.1
    ports:
      - 8080/http
    app-mount:
      destination: /usr/share/nginx/html

tooling:
  do-i-exist:
    service: web2
    cmd: echo icachethereforeiam

plugins:
  "@lando/core": ../..
