name: Deploy GitHub Artifacts

on:
  workflow_call:
    inputs:
      download-name:
        default:
        description: The artifact name to download for checksumming
        required: false
        type: string
      download-pattern:
        default:
        description: The artifact pattern to download for checksumming
        required: false
        type: string

jobs:
  deploy-releases:
    runs-on: ubuntu-24.04
    env:
      TERM: xterm
    steps:
      - name: Create paths
        run: mkdir -p /tmp/deploy-releases/${{ github.sha }}
      - name: Download releases
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.download-name }}
          merge-multiple: true
          path: /tmp/deploy-releases/${{ github.sha }}
          pattern: ${{ inputs.download-pattern }}
      - name: Upload releases to GitHub Releases
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: /tmp/deploy-releases/${{ github.sha }}/*
          fail_on_unmatched_files: true
