name: Setup Linux Tests

on:
  pull_request:

jobs:
  leia-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      fail-fast: false
      matrix:
        leia-test:
          - setup-linux
        node-version:
          - "20"
        os:
          - ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
          cache: npm
      - name: Bundle Deps
        uses: lando/prepare-release-action@v3
        with:
          lando-plugin: true
          version: dev
          sync: false
      - name: Install pkg dependencies
        run: npm clean-install --prefer-offline --frozen-lockfile --production
      - name: Package into node binary
        uses: lando/pkg-action@v5
        id: pkg-action
        with:
          entrypoint: bin/lando
          node-version: ${{ matrix.node-version }}
          options: --options dns-result-order=ipv4first
          upload: false
          pkg: "@yao-pkg/pkg@5.16.1"
      - name: Install full deps
        run: npm clean-install --prefer-offline --frozen-lockfile
      - name: Setup lando ${{ steps.pkg-action.outputs.file }}
        uses: lando/setup-lando@v3
        with:
          auto-setup: false
          lando-version: ${{ steps.pkg-action.outputs.file }}
          telemetry: false
      - name: Run Leia Tests
        uses: lando/run-leia-action@v2
        with:
          leia-test: "./examples/${{ matrix.leia-test }}/README.md"
          cleanup-header: "Destroy tests"
          shell: bash
          stdin: true
