name: Sign Binary

on:
  workflow_call:
    inputs:
      file:
        description: The file to sign
        required: true
        type: string
      os:
        description: The OS to sign for
        required: false
        type: string
        default:
    secrets:
      certificate-data:
        description: "A `base64` encoded string of your `p12` or `pfx` cert contents. Note: if you use KeyLocker, this will be the base64 encoded client certificate (`SM_CLIENT_CERT_FILE`)"
        required: true
      certificate-password:
        description: "The password to unlock the certificate-data"
        required: true
      apple-notary-password:
        description: "The Apple Developer account password to use in notarization"
        required: false
      apple-notary-user:
        description: "The Apple Developer account email to use in notarization"
        required: false
      keylocker-api-key:
        description: "The API key to use for KeyLocker"
        required: false
      keylocker-cert-sha1-hash:
        description: "The SHA1 hash of the certificate to use for KeyLocker"
        required: false
      keylocker-keypair-alias:
        description: "The alias of the keypair to use for KeyLocker"
        required: false

jobs:
  codesign-binary:
    runs-on: ${{
      (contains(inputs.os, 'linux') || contains(inputs.file, 'linux')) && 'ubuntu-24.04' ||
      (contains(inputs.os, 'macos') || contains(inputs.file, 'macos')) && 'macos-14' ||
      (contains(inputs.os, 'win') || contains(inputs.file, 'win')) && 'windows-2022'}}
    env:
      TERM: xterm
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Ensure path
      run: mkdir -p /tmp/${{ github.sha }}
    - name: Download binaries
      uses: actions/download-artifact@v4
      with:
        pattern: lando-*
        path: /tmp/${{ github.sha }}
        merge-multiple: true
    - name: Ensure path
      run: |
        ls -lsa /tmp/${{ github.sha }}
    - name: Sign and Notarize
      uses: lando/code-sign-action@v2
      id: code-sign-action
      with:
        apple-notary-user: ${{ secrets.APPLE }}
        apple-notary-password: ${{ secrets.apple-notary-password }}
        apple-product-id: dev.lando.cli
        apple-team-id: FY8GAUX282
        certificate-data: ${{ secrets.certificate-data }}
        certificate-password: ${{ secrets.certificate-password }}
        file: /tmp/${{ github.sha }}/${{ inputs.file }}
        keylocker-api-key: ${{ secrets.keylocker-api-key }}
        keylocker-cert-sha1-hash: ${{ secrets.keylocker-cert-sha1-hash }}
        keylocker-host: https://clientauth.one.digicert.com
        keylocker-keypair-alias: ${{ secrets.keylocker-keypair-alias }}
        options: ${{ runner.os == 'macOS' && '--options runtime --entitlements entitlements.xml' || '' }}
