name: Sign Binary

on:
  workflow_call:
    inputs:
      download-name:
        default:
        description: The artifact name to download for checksumming
        required: false
        type: string
      download-pattern:
        default:
        description: The artifact pattern to download for checksumming
        required: false
        type: string
      file:
        description: The file to sign
        required: true
        type: string
      os:
        description: The OS to sign for
        required: false
        type: string
        default:
    secrets:
      certificate-data:
        description: "A `base64` encoded string of your `p12` or `pfx` cert contents."
        required: false
      certificate-password:
        description: "The password to unlock the certificate-data"
        required: false
      apple-notary-password:
        description: "The Apple Developer account password to use in notarization"
        required: false
      apple-notary-user:
        description: "The Apple Developer account email to use in notarization"
        required: false
      azure-client-id:
        description: "The Azure application client ID to use for Azure Artifact Signing"
        required: false
      azure-subscription-id:
        description: "The Azure subscription ID to use for Azure Artifact Signing"
        required: false
      azure-tenant-id:
        description: "The Azure tenant ID to use for Azure Artifact Signing"
        required: false

jobs:
  codesign-binary:
    permissions:
      contents: read
      id-token: write
    runs-on: ${{
      (contains(inputs.os, 'linux') || contains(inputs.file, 'linux')) && 'ubuntu-24.04' ||
      (contains(inputs.os, 'macos') || contains(inputs.file, 'macos')) && 'macos-15' ||
      (contains(inputs.os, 'win') || contains(inputs.file, 'win')) && 'windows-2022'}}
    env:
      TERM: xterm
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Create paths
        run: mkdir -p /tmp/sign/${{ github.sha }}
      - name: Download binaries
        id: download-artifacts
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.download-name }}
          merge-multiple: true
          path: /tmp/sign/${{ github.sha }}
          pattern: ${{ inputs.download-pattern }}
      - name: Sign and Notarize
        id: code-sign-action
        if: runner.os == 'macOS' || runner.os == 'Windows'
        uses: lando/code-sign-action@v3
        with:
          apple-notary-user: ${{ secrets.apple-notary-user }}
          apple-notary-password: ${{ secrets.apple-notary-password }}
          apple-product-id: dev.lando.cli
          apple-team-id: 466VYKC9T5
          azure-client-id: ${{ secrets.azure-client-id }}
          azure-signing-account-name: lando
          azure-signing-endpoint: https://eus.codesigning.azure.net/
          azure-subscription-id: ${{ secrets.azure-subscription-id }}
          azure-tenant-id: ${{ secrets.azure-tenant-id }}
          certificate-data: ${{ secrets.certificate-data }}
          certificate-id: ${{ runner.os == 'Windows' && 'lando' || '466VYKC9T5' }}
          certificate-password: ${{ secrets.certificate-password }}
          file: ${{ steps.download-artifacts.outputs.download-path }}/${{ inputs.file }}${{ runner.os == 'Windows' && !endsWith(inputs.file, '.exe') && '.exe' || '' }}
          options: ${{ runner.os == 'macOS' && '--options runtime --entitlements "$GITHUB_WORKSPACE/entitlements.xml"' || '' }}
          signtool: ${{ runner.os == 'Windows' && 'azure' || 'auto' }}
      - name: Upload signed binaries
        uses: actions/upload-artifact@v7
        with:
          name: signed-${{ inputs.file }}
          path: /tmp/sign/${{ github.sha }}/${{ inputs.file }}${{ runner.os == 'Windows' && !endsWith(inputs.file, '.exe') && '.exe' || '' }}
          if-no-files-found: error
          retention-days: 1
